		dc.w 9
		dc.l Obj_Ring
		dc.l Map_Ring
		dc.w $A6BC
		dc.l Obj_Bumper
		dc.l Map_PachinkoBumper
		dc.w $62CD
		dc.l Obj_PachinkoTriangleBumper+$1000000
		dc.l Map_PachinkoTriangleBumper
		dc.w $E2EB
		dc.l Obj_PachinkoFlipper+$4000000
		dc.l Map_PachinkoFlipper
		dc.w $832F
		dc.l Obj_PachinkoEnergyTrap
		dc.l Map_PachinkoEnergyTrap
		dc.w $2352
		dc.l Obj_Pachinko_Platform
		dc.l Map_PachinkoPlatform
		dc.w $2358
		dc.l Obj_PachinkoInvisibleUnknown
		dc.l Map_PachinkoInvisibleUnknown
		dc.w $E364
		dc.l Obj_GumballItem
		dc.l Map_PachinkoFItem
		dc.w $6378
		dc.l Obj_PachinkoItemOrb
		dc.l Map_PachinkoItemOrb
		dc.w $E364
