		dc.w Debug_AIZ1-DebugOffs
		dc.w Debug_AIZ2-DebugOffs
		dc.w Debug_HCZ-DebugOffs
		dc.w Debug_HCZ-DebugOffs
		dc.w Debug_MGZ-DebugOffs
		dc.w Debug_MGZ-DebugOffs
		dc.w Debug_CNZ-DebugOffs
		dc.w Debug_CNZ-DebugOffs
		dc.w Debug_FBZ1-DebugOffs
		dc.w Debug_FBZ2-DebugOffs
		dc.w Debug_ICZ1-DebugOffs
		dc.w Debug_ICZ2-DebugOffs
		dc.w Debug_LBZ1-DebugOffs
		dc.w Debug_LBZ2-DebugOffs
		dc.w Debug_MHZ-DebugOffs
		dc.w Debug_MHZ-DebugOffs
		dc.w Debug_SOZ1-DebugOffs
		dc.w Debug_SOZ2-DebugOffs
		dc.w Debug_LRZ1-DebugOffs
		dc.w Debug_LRZ2-DebugOffs
		dc.w Debug_SSZ-DebugOffs
		dc.w Debug_SSZ-DebugOffs
		dc.w Debug_DEZ1-DebugOffs
		dc.w Debug_DEZ2-DebugOffs
		dc.w Debug_DDZ-DebugOffs
		dc.w DebugDEZBoss-DebugOffs
		dc.w Debug_Ending-DebugOffs
		dc.w Debug_Ending-DebugOffs
		dc.w Debug_ALZ-DebugOffs
		dc.w Debug_ALZ-DebugOffs
		dc.w Debug_BPZ-DebugOffs
		dc.w Debug_BPZ-DebugOffs
		dc.w Debug_DPZ-DebugOffs
		dc.w Debug_DPZ-DebugOffs
		dc.w Debug_CGZ-DebugOffs
		dc.w Debug_CGZ-DebugOffs
		dc.w Debug_EMZ-DebugOffs
		dc.w Debug_EMZ-DebugOffs
		dc.w Debug_Gumball_Special-DebugOffs
		dc.w Debug_Gumball_Special-DebugOffs
		dc.w Debug_Pachinko_Special-DebugOffs
		dc.w Debug_Pachinko_Special-DebugOffs
		dc.w Debug_Gumball_Special-DebugOffs
		dc.w Debug_Gumball_Special-DebugOffs
		dc.w Debug_HPZ-DebugOffs
		dc.w Debug_HPZ-DebugOffs
		dc.w Debug_Gumball_Special-DebugOffs
		dc.w Debug_Gumball_Special-DebugOffs
