		dc.l Obj_Ring				; 0
		dc.l Obj_Monitor			; 1
		dc.l Obj_PathSwap			; 2
		dc.l Obj_MHZTwistedVine			; 3
		dc.l Obj_CollapsingPlatform		; 4
		dc.l Obj_AIZLRZEMZRock			; 5
		dc.l Obj_MHZPulleyLift			; 6
		dc.l Obj_Spring				; 7
		dc.l Obj_Spikes				; 8
		dc.l Obj_MHZCurledVine			; 9
		dc.l Obj_MHZStickyVine			; 10
		dc.l Obj_MHZSwingBarHorizontal		; 11
		dc.l Obj_MHZSwingBarVertical		; 12
		dc.l Obj_BreakableWall			; 13
		dc.l Obj_TwistedRamp			; 14
		dc.l Obj_CollapsingBridge		; 15
		dc.l Obj_MHZSwingVine			; 16
		dc.l Obj_MHZMushroomPlatform		; 17
		dc.l Obj_MHZMushroomParachute		; 18
		dc.l Obj_MHZMushroomCatapult		; 19
		dc.l Obj_Updraft			; 20
		dc.l Obj_LRZCorkscrew			; 21
		dc.l Obj_LRZWallRide			; 22
		dc.l Obj_LRZSinkingRock			; 23
		dc.l Obj_LRZFallingSpike		; 24
		dc.l Obj_LRZDoor			; 25
		dc.l Obj_LRZBigDoor			; 26
		dc.l Obj_LRZFireballLauncher		; 27
		dc.l Obj_LRZButtonHorizontal		; 28
		dc.l Obj_LRZShootingTrigger		; 29
		dc.l Obj_LRZDashElevator		; 30
		dc.l Obj_LRZLavaFall			; 31
		dc.l Obj_LRZSwingingSpikeBall		; 32
		dc.l Obj_LRZSmashingSpikePlatform	; 33
		dc.l Obj_LRZSpikeBall			; 34
		dc.l Obj_MHZMushroomCap			; 35
		dc.l Obj_AutomaticTunnel		; 36
		dc.l Obj_LRZChainedPlatforms		; 37
		dc.l Obj_AutoSpin			; 38
		dc.l Obj_S2LavaMarker			; 39
		dc.l Obj_InvisibleBlock			; 40
		dc.l Obj_LRZFlameThrower		; 41
		dc.l Obj_CorkFloor			; 42
		dc.l Obj_LRZOrbitingSpikeBallHorizontal	; 43
		dc.l Obj_LRZOrbitingSpikeBallVertical	; 44
		dc.l Obj_LRZSolidMovingPlatforms	; 45
		dc.l Obj_LRZSolidRock			; 46
		dc.l Obj_StillSprite			; 47
		dc.l Obj_AnimatedStillSprite		; 48
		dc.l Obj_LRZCollapsingBridge		; 49
		dc.l Obj_LRZTurbineSprites		; 50
		dc.l Obj_Button				; 51
		dc.l Obj_StarPost			; 52
		dc.l Obj_AIZForegroundPlant		; 53
		dc.l Obj_HCZBreakableBar		; 54
		dc.l Obj_LRZSpikeBallLauncher		; 55
		dc.l Obj_SOZQuicksand			; 56
		dc.l Obj_SOZSpawningSandBlocks		; 57
		dc.l Obj_SOZPathSwap			; 58
		dc.l Obj_SOZLoopFallthrough		; 59
		dc.l Obj_Door				; 60
		dc.l Obj_RetractingSpring		; 61
		dc.l Obj_SOZPushableRock		; 62
		dc.l Obj_SOZSpringVine			; 63
		dc.l Obj_SOZRisingSandWall		; 64
		dc.l Obj_SOZLightSwitch			; 65
		dc.l Obj_SOZFloatingPillar		; 66
		dc.l Obj_SOZSwingingPlatform		; 67
		dc.l Obj_SOZBreakableSandRock		; 68
		dc.l Obj_SOZPushSwitch			; 69
		dc.l Obj_SOZDoor			; 70
		dc.l Obj_SOZSandCork			; 71
		dc.l Obj_SOZRapelWire			; 72
		dc.l Obj_SOZSolidSprites		; 73
		dc.l Obj_DEZFloatingPlatform		; 74
		dc.l Obj_DEZTiltingBridge		; 75
		dc.l Obj_DEZHangCarrier			; 76
		dc.l Obj_DEZTorpedoLauncher		; 77
		dc.l Obj_DEZLiftPad			; 78
		dc.l Obj_DEZStaircase			; 79
		dc.l Obj_DEZConveyorBelt		; 80
		dc.l Obj_FloatingPlatform		; 81
		dc.l Obj_DEZLightning			; 82
		dc.l Obj_DEZConveyorPad			; 83
		dc.l Obj_Bubbler			; 84
		dc.l Obj_DEZEnergyBridge		; 85
		dc.l Obj_DEZEnergyBridgeCurved		; 86
		dc.l Obj_DEZTunnelLauncher		; 87
		dc.l Obj_DEZGravitySwitch		; 88
		dc.l Obj_DEZTeleporter			; 89
		dc.l Obj_DEZGravityTube			; 90
		dc.l Obj_DEZGravitySwap			; 91
		dc.l Obj_DEZGravityHub			; 92
		dc.l Obj_DEZRetractingSpring		; 93
		dc.l Obj_DEZHoverMachine		; 94
		dc.l Obj_DEZGravityRoom			; 95
		dc.l Obj_DEZBumperWall			; 96
		dc.l Obj_DEZGravityPuzzle		; 97
		dc.l Obj_Ring				; 98
		dc.l Obj_Ring				; 99
		dc.l Obj_Ring				; 100
		dc.l Obj_Ring				; 101
		dc.l Obj_Ring				; 102
		dc.l Obj_Ring				; 103
		dc.l Obj_Ring				; 104
		dc.l Obj_Ring				; 105
		dc.l Obj_InvisibleHurtBlockHorizontal	; 106
		dc.l Obj_InvisibleHurtBlockVertical	; 107
		dc.l Obj_TensionBridge			; 108
		dc.l Obj_InvisibleShockBlock		; 109
		dc.l Obj_InvisibleLavaBlock		; 110
		dc.l Obj_Ring				; 111
		dc.l Obj_Ring				; 112
		dc.l Obj_Ring				; 113
		dc.l Obj_Ring				; 114
		dc.l Obj_Ring				; 115
		dc.l Obj_SSZRetractingSpring		; 116
		dc.l Obj_SSZSwingingCarrier		; 117
		dc.l Obj_SSZRotatingPlatform		; 118
		dc.l Obj_SSZCutsceneBridge		; 119
		dc.l Obj_FBZDEZPlayerLauncher		; 120
		dc.l Obj_SSZHPZTeleporter		; 121
		dc.l Obj_SSZElevatorBar			; 122
		dc.l Obj_SSZCollapsingBridgeDiagonal	; 123
		dc.l Obj_SSZCollapsingBridge		; 124
		dc.l Obj_SSZBouncyCloud			; 125
		dc.l Obj_SSZCollapsingColumn		; 126
		dc.l Obj_SSZFloatingPlatform		; 127
		dc.l Obj_HiddenMonitor			; 128
		dc.l Obj_EggCapsule			; 129
		dc.l Obj_CutsceneKnuckles		; 130
		dc.l Obj_CutsceneButton			; 131
		dc.l Obj_AIZPlaneIntro			; 132
		dc.l Obj_SSEntryRing			; 133
		dc.l Obj_GumballMachine			; 134
		dc.l Obj_GumballTriangleBumper		; 135
		dc.l Obj_CNZWaterLevelCorkFloor		; 136
		dc.l Obj_CNZWaterLevelButton		; 137
		dc.l Obj_FBZExitHall			; 138
		dc.l Obj_SpriteMask			; 139
		dc.l Obj_Madmole			; 140
		dc.l Obj_Mushmeanie			; 141
		dc.l Obj_Dragonfly			; 142
		dc.l Obj_Butterdroid			; 143
		dc.l Obj_Cluckoid			; 144
		dc.l Obj_MHZMinibossTree		; 145
		dc.l Obj_MHZMiniboss			; 146
		dc.l Obj_MHZEndBoss			; 147
		dc.l Obj_Skorp				; 148
		dc.l Obj_Sandworm			; 149
		dc.l Obj_Rockn				; 150
		dc.l Obj_SOZMiniboss			; 151
		dc.l Obj_SOZEndBoss			; 152
		dc.l Obj_Fireworm			; 153
		dc.l Obj_Iwamodoki			; 154
		dc.l Obj_Toxomister			; 155
		dc.l Obj_LRZRockCrusher			; 156
		dc.l Obj_LRZMiniboss			; 157
		dc.l Obj_LRZ3Autoscroll			; 158
		dc.l Obj_Ring				; 159
		dc.l Obj_EggRobo			; 160
		dc.l Obj_SSZGHZBoss			; 161
		dc.l Obj_SSZMTZBoss			; 162
		dc.l Obj_SSZEndBoss			; 163
		dc.l Obj_Spikebonker			; 164
		dc.l Obj_Chainspike			; 165
		dc.l Obj_DEZMiniboss			; 166
		dc.l Obj_DEZEndBoss			; 167
		dc.l Obj_MHZ1CutsceneKnuckles		; 168
		dc.l Obj_MHZ1CutsceneButton		; 169
		dc.l Obj_SOZGhosts			; 170
		dc.l Obj_SOZGhostCapsuleLoadArt		; 171
		dc.l Obj_SOZGhostCapsule		; 172
		dc.l Obj_LRZ3Platform			; 173
		dc.l Obj_LRZ2CutsceneKnuckles		; 174
		dc.l Obj_SSZCutsceneButton		; 175
		dc.l Obj_HPZMasterEmerald		; 176
		dc.l Obj_HPZPaletteControl		; 177
		dc.l Obj_KnuxFinalBossCrane		; 178
		dc.l Obj_StartNewLevel			; 179
		dc.l Obj_HPZSuperEmerald		; 180
		dc.l Obj_HPZSSEntryControl		; 181
		dc.l Obj_DDZEndBoss			; 182
		dc.l Obj_DDZAsteroid			; 183
		dc.l Obj_DDZMissile			; 184
