		dc.l Obj_Ring				; 0
		dc.l Obj_Monitor			; 1
		dc.l Obj_PathSwap			; 2
		dc.l Obj_AIZHollowTree			; 3
		dc.l Obj_CollapsingPlatform		; 4
		dc.l Obj_AIZLRZEMZRock			; 5
		dc.l Obj_AIZRideVine			; 6
		dc.l Obj_Spring				; 7
		dc.l Obj_Spikes				; 8
		dc.l Obj_AIZ1Tree			; 9
		dc.l Obj_AIZ1ZiplinePeg			; 10
		dc.l Obj_Ring				; 11
		dc.l Obj_AIZGiantRideVine		; 12
		dc.l Obj_BreakableWall			; 13
		dc.l Obj_TwistedRamp			; 14
		dc.l Obj_CollapsingBridge		; 15
		dc.l Obj_LBZTubeElevator		; 16
		dc.l Obj_LBZMovingPlatform		; 17
		dc.l Obj_LBZUnusedElevator		; 18
		dc.l Obj_LBZExplodingTrigger		; 19
		dc.l Obj_LBZTriggerBridge		; 20
		dc.l Obj_LBZPlayerLauncher		; 21
		dc.l Obj_LBZFlameThrower		; 22
		dc.l Obj_LBZRideGrapple			; 23
		dc.l Obj_LBZCupElevator			; 24
		dc.l Obj_LBZCupElevatorPole		; 25
		dc.l Obj_LBZUnusedTiltingBridge		; 26
		dc.l Obj_LBZPipePlug			; 27
		dc.l Obj_Ring				; 28
		dc.l Obj_LBZUnusedBarPlatform		; 29
		dc.l Obj_LBZSpinLauncher		; 30
		dc.l Obj_LBZLoweringGrapple		; 31
		dc.l Obj_MGZLBZSmashingPillar		; 32
		dc.l Obj_LBZGateLaser			; 33
		dc.l Obj_LBZAlarm			; 34
		dc.l Obj_LBZUnusedForceFall		; 35
		dc.l Obj_AutomaticTunnel		; 36
		dc.l Obj_Ring				; 37
		dc.l Obj_AutoSpin			; 38
		dc.l Obj_S2LavaMarker			; 39
		dc.l Obj_InvisibleBlock			; 40
		dc.l Obj_AIZDisappearingFloor		; 41
		dc.l Obj_CorkFloor			; 42
		dc.l Obj_AIZFlippingBridge		; 43
		dc.l Obj_AIZCollapsingLogBridge		; 44
		dc.l Obj_AIZFallingLog			; 45
		dc.l Obj_AIZSpikedLog			; 46
		dc.l Obj_StillSprite			; 47
		dc.l Obj_AnimatedStillSprite		; 48
		dc.l Obj_LBZRollingDrum			; 49
		dc.l Obj_AIZDrawBridge			; 50
		dc.l Obj_Button				; 51
		dc.l Obj_StarPost			; 52
		dc.l Obj_AIZForegroundPlant		; 53
		dc.l Obj_HCZBreakableBar		; 54
		dc.l Obj_HCZWaterRush			; 55
		dc.l Obj_HCZCGZFan			; 56
		dc.l Obj_HCZLargeFan			; 57
		dc.l Obj_HCZHandLauncher		; 58
		dc.l Obj_HCZWaterWall			; 59
		dc.l Obj_Door				; 60
		dc.l Obj_RetractingSpring		; 61
		dc.l Obj_HCZConveyorBelt		; 62
		dc.l Obj_HCZConveryorSpike		; 63
		dc.l Obj_HCZBlock			; 64
		dc.l Obj_CNZBalloon			; 65
		dc.l Obj_CNZCannon			; 66
		dc.l Obj_CNZRisingPlatform		; 67
		dc.l Obj_CNZTrapDoor			; 68
		dc.l Obj_CNZLightBulb			; 69
		dc.l Obj_CNZHoverFan			; 70
		dc.l Obj_CNZCylinder			; 71
		dc.l Obj_CNZVacuumTube			; 72
		dc.l Obj_CNZGiantWheel			; 73
		dc.l Obj_Bumper				; 74
		dc.l Obj_CNZTriangleBumpers		; 75
		dc.l Obj_CNZSpiralTube			; 76
		dc.l Obj_CNZBarberPoleSprite		; 77
		dc.l Obj_CNZWireCage			; 78
		dc.l Obj_SinkingMud			; 79
		dc.l Obj_MGZTwistingLoop		; 80
		dc.l Obj_FloatingPlatform		; 81
		dc.l Obj_MGZLBZSmashingPillar		; 82
		dc.l Obj_MGZSwingingPlatform		; 83
		dc.l Obj_Bubbler			; 84
		dc.l Obj_MGZHeadTrigger			; 85
		dc.l Obj_MGZMovingSpikePlatform		; 86
		dc.l Obj_MGZTriggerPlatform		; 87
		dc.l Obj_MGZSwingingSpikeBall		; 88
		dc.l Obj_MGZDashTrigger			; 89
		dc.l Obj_MGZPulley			; 90
		dc.l Obj_MGZTopPlatform			; 91
		dc.l Obj_MGZTopLauncher			; 92
		dc.l Obj_CGZTriangleBumpers		; 93
		dc.l Obj_CGZBladePlatform		; 94
		dc.l Obj_2PRetractingSpring		; 95
		dc.l Obj_BPZElephantBlock		; 96
		dc.l Obj_BPZBalloon			; 97
		dc.l Obj_DPZDisolvingSandBar		; 98
		dc.l Obj_DPZButton			; 99
		dc.l Obj_2PItem				; 100
		dc.l Obj_2PGoalMarker			; 101
		dc.l Obj_EMZDripper			; 102
		dc.l Obj_HCZSnakeBlocks			; 103
		dc.l Obj_HCZSpinningColumn		; 104
		dc.l Obj_HCZTwistingLoop		; 105
		dc.l Obj_InvisibleHurtBlockHorizontal	; 106
		dc.l Obj_InvisibleHurtBlockVertical	; 107
		dc.l Obj_TensionBridge			; 108
		dc.l Obj_HCZWaterSplash			; 109
		dc.l Obj_WaterDrop			; 110
		dc.l Obj_FBZWireCage			; 111
		dc.l Obj_FBZWireCageStationary		; 112
		dc.l Obj_FBZFloatingPlatform		; 113
		dc.l Obj_FBZChainLink			; 114
		dc.l Obj_FBZMagneticSpikeBall		; 115
		dc.l Obj_FBZMagneticPlatform		; 116
		dc.l Obj_FBZSnakePlatform		; 117
		dc.l Obj_FBZBentPipe			; 118
		dc.l Obj_FBZRotatingPlatform		; 119
		dc.l Obj_FBZDEZPlayerLauncher		; 120
		dc.l Obj_FBZDisappearingPlatform	; 121
		dc.l Obj_FBZScrewDoor			; 122
		dc.l Obj_FBZSpinningPole		; 123
		dc.l Obj_FBZPropeller			; 124
		dc.l Obj_FBZPiston			; 125
		dc.l Obj_FBZPlatformBlocks		; 126
		dc.l Obj_FBZMissileLauncher		; 127
		dc.l Obj_HiddenMonitor			; 128
		dc.l Obj_EggCapsule			; 129
		dc.l Obj_CutsceneKnuckles		; 130
		dc.l Obj_CutsceneButton			; 131
		dc.l Obj_AIZPlaneIntro			; 132
		dc.l Obj_SSEntryRing			; 133
		dc.l Obj_GumballMachine			; 134
		dc.l Obj_GumballTriangleBumper		; 135
		dc.l Obj_CNZWaterLevelCorkFloor		; 136
		dc.l Obj_CNZWaterLevelButton		; 137
		dc.l Obj_FBZExitHall			; 138
		dc.l Obj_SpriteMask			; 139
		dc.l Obj_Bloominator			; 140
		dc.l Obj_Rhinobot			; 141
		dc.l Obj_MonkeyDude			; 142
		dc.l Obj_CaterKillerJr			; 143
		dc.l Obj_AIZMinibossCutscene		; 144
		dc.l Obj_AIZMiniboss			; 145
		dc.l Obj_AIZEndBoss			; 146
		dc.l Obj_Jawz				; 147
		dc.l Obj_Blastoid			; 148
		dc.l Obj_Buggernaut			; 149
		dc.l Obj_TurboSpiker			; 150
		dc.l Obj_MegaChopper			; 151
		dc.l Obj_Poindexter			; 152
		dc.l Obj_HCZMiniboss			; 153
		dc.l Obj_HCZEndBoss			; 154
		dc.l Obj_BubblesBadnik			; 155
		dc.l Obj_Spiker				; 156
		dc.l Obj_Mantis				; 157
		dc.l Obj_Tunnelbot			; 158
		dc.l Obj_MGZMiniboss			; 159
		dc.l Obj_MGZ2DrillingRobotnik		; 160
		dc.l Obj_MGZEndBoss			; 161
		dc.l Obj_MGZEndBossKnux			; 162
		dc.l Obj_Clamer				; 163
		dc.l Obj_Sparkle			; 164
		dc.l Obj_Batbot				; 165
		dc.l Obj_CNZMiniboss			; 166
		dc.l Obj_CNZEndBoss			; 167
		dc.l Obj_Blaster			; 168
		dc.l Obj_TechnoSqueek			; 169
		dc.l Obj_FBZMiniboss			; 170
		dc.l Obj_FBZ2Subboss			; 171
		dc.l Obj_FBZEndBoss			; 172
		dc.l Obj_Penguinator			; 173
		dc.l Obj_StarPointer			; 174
		dc.l Obj_ICZCrushingColumn		; 175
		dc.l Obj_ICZPathFollowPlatform		; 176
		dc.l Obj_ICZBreakableWall		; 177
		dc.l Obj_ICZFreezer			; 178
		dc.l Obj_ICZSegmentColumn		; 179
		dc.l Obj_ICZSwingingPlatform		; 180
		dc.l Obj_ICZStalagtite			; 181
		dc.l Obj_ICZIceCube			; 182
		dc.l Obj_ICZIceSpikes			; 183
		dc.l Obj_ICZHarmfulIce			; 184
		dc.l Obj_ICZSnowPile			; 185
		dc.l Obj_ICZTensionPlatform		; 186
		dc.l Obj_ICZIceBlock			; 187
		dc.l Obj_ICZMiniboss			; 188
		dc.l Obj_ICZEndBoss			; 189
		dc.l Obj_SnaleBlaster			; 190
		dc.l Obj_Ribot				; 191
		dc.l Obj_Orbinaut			; 192
		dc.l Obj_Corkey				; 193
		dc.l Obj_Flybot767			; 194
		dc.l Obj_LBZ1Robotnik			; 195
		dc.l Obj_LBZMinibossBox			; 196
		dc.l Obj_LBZMinibossBoxKnux		; 197
		dc.l Obj_LBZ2RobotnikShip		; 198
		dc.l Obj_Ring				; 199
		dc.l Obj_LBZKnuxPillar			; 200
		dc.l Obj_LBZMiniboss			; 201
		dc.l Obj_LBZFinalBoss1			; 202
		dc.l Obj_LBZEndBoss			; 203
		dc.l Obj_LBZFinalBoss2			; 204
		dc.l Obj_LBZFinalBossKnux		; 205
		dc.l Obj_FBZExitDoor			; 206
		dc.l Obj_FBZEggPrison			; 207
		dc.l Obj_FBZSpringPlunger		; 208
		dc.l Obj_Ring				; 209
		dc.l Obj_Ring				; 210
		dc.l Obj_Ring				; 211
		dc.l Obj_Ring				; 212
		dc.l Obj_Ring				; 213
		dc.l Obj_Ring				; 214
		dc.l Obj_Ring				; 215
		dc.l Obj_Ring				; 216
		dc.l Obj_Ring				; 217
		dc.l Obj_Ring				; 218
		dc.l Obj_Ring				; 219
		dc.l Obj_Ring				; 220
		dc.l Obj_Ring				; 221
		dc.l Obj_Ring				; 222
		dc.l Obj_Ring				; 223
		dc.l Obj_FBZWallMissile			; 224
		dc.l Obj_FBZMine			; 225
		dc.l Obj_FBZElevator			; 226
		dc.l Obj_FBZTrapSpring			; 227
		dc.l Obj_FBZFlamethrower		; 228
		dc.l Obj_FBZSpiderCrane			; 229
		dc.l Obj_PachinkoTriangleBumper		; 230
		dc.l Obj_PachinkoFlipper		; 231
		dc.l Obj_PachinkoEnergyTrap		; 232
		dc.l Obj_PachinkoInvisibleUnknown	; 233
		dc.l Obj_Pachinko_Platform		; 234
		dc.l Obj_GumballItem			; 235
		dc.l Obj_PachinkoMagnetOrb		; 236
		dc.l Obj_PachinkoItemOrb		; 237
		dc.l Obj_Ring				; 238
		dc.l Obj_Ring				; 239
		dc.l Obj_Ring				; 240
		dc.l Obj_Ring				; 241
		dc.l Obj_Ring				; 242
		dc.l Obj_Ring				; 243
		dc.l Obj_Ring				; 244
		dc.l Obj_Ring				; 245
		dc.l Obj_Ring				; 246
		dc.l Obj_Ring				; 247
		dc.l Obj_Ring				; 248
		dc.l Obj_Ring				; 249
		dc.l Obj_Ring				; 250
		dc.l Obj_Ring				; 251
		dc.l Obj_Ring				; 252
		dc.l Obj_Ring				; 253
		dc.l Obj_Ring				; 254
		dc.l Obj_FBZMagneticPendulum		; 255
