; Palette pointers

		dc.l Pal_Unknown1
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_Unknown2
		dc.w Normal_palette_line_2&$FFFF
		dc.w 7
		dc.l Pal_Unknown3
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_SonicTails
		dc.w Normal_palette&$FFFF
		dc.w 7
		dc.l Pal_S2Menu
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_Knuckles
		dc.w Normal_palette_line_2&$FFFF
		dc.w 7
		dc.l Pal_Unknown1
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_Unknown1
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_Unknown1
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_Unknown1
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_AIZIntro
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_AIZFire
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_HCZ1
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_HCZ2
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_MGZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_MGZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_CNZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_CNZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_FBZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_FBZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ICZ1
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ICZ2
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_LBZ1
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_LBZ2
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ALZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_BPZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_BPZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_AIZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_AIZ_Water
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_AIZ2_Water
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_LBZ_Water
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_LBZ_Water
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_LBZ_Water2
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_AIZBoss
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_HCZ1_Water
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_HCZ2_Water
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_Gumball_Special
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_DPZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_CGZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_EMZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_Pachinko_Special
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_Slot_Special
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
		dc.l Pal_ICZ2_Water
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_CNZ_Water
		dc.w Normal_palette&$FFFF
		dc.w $1F
		dc.l Pal_AIZ
		dc.w Normal_palette_line_2&$FFFF
		dc.w $17
